### ISSUE TITLE
Fatal error on EDD 3.0

### ISSUE THREAD

**Issue by mihaijoldis** [awesomemotive/edd-hide-download#28]
Reported by a customer here: https://secure.helpscout.net/conversation/1955583730/2063648/
The error message can be seen in that ticket. We don't have exact replication steps unfortunately but locally once I activated it I did not see the error.

**Comment by robincornett** [comment]
Here's the specific error log from the ticket:
```
"type": "error",
"date": "2022-07-21T13:02:19.000Z",
"severity": "error",
"client": "130.132.173.47:0] PHP Fatal error: Uncaught TypeError: array_merge(): Argument #2 must be of type array, null given in /nas/content/live/wp-content/plugins/edd-hide-download/edd-hide-download.php:355\\nStack trace:\\n#0 /nas/content/live/wp-content/plugins/edd-hide-download/edd-hide-download.php(355): array_merge(Array, NULL)\\n#1 /nas/content/live/wp-includes/class-wp-hook.php(307): EDD_Hide_Download->pre_get_posts(Object(WP_Query))\\n#2 /nas/content/live/wp-includes/class-wp-hook.php(331): WP_Hook->apply_filters(NULL, Array)\\n#3 /nas/content/live/wp-includes/plugin.php(524): WP_Hook->do_action(Array)\\n#4 /nas/content/live/wp-includes/class-wp-query.php(1805): do_action_ref_array('pre_get_posts', Array)\\n#5 /nas/content/live/wp-includes/class-wp-query.php(3586): WP_Query->get_posts()\\n#6 /nas/content/live/wp-includes/class-wp-query.php(3718): WP_Query->query(Array)\\n#7 /nas/content/live/wp-content/plugins/edd-hide-download/edd-hide-download.php(278): WP_Query->__construct(Array)\\n#8 /nas/content/live/wp-content/plugins/edd-hide-download/edd-hide-download.php(189): EDD_Hide_Download->query_hidden_downloads()\\n#9 /nas/content/live/wp-content/plugins/edd-hide-download/edd-hide-download.php(102): EDD_Hide_Download->hooks()\\n#10 /nas/content/live/wp-content/plugins/edd-hide-download/edd-hide-download.php(406): EDD_Hide_Download::get_instance()\\n#11 [internal function",
"message": "PHP Fatal error: Uncaught TypeError: array_merge(): Argument #2 must be of type array, null given in /nas/content/live/wp-content/plugins/edd-hide-download/edd-hide-download.php:355\\nStack trace:\\n#0 /nas/content/live/wp-content/plugins/edd-hide-download/edd-hide-download.php(355): array_merge(Array, NULL)\\n#1 /nas/content/live/wp-includes/class-wp-hook.php(307): EDD_Hide_Download->pre_get_posts(Object(WP_Query))\\n#2 /nas/content/live/wp-includes/class-wp-hook.php(331): WP_Hook->apply_filters(NULL, Array)\\n#3 /nas/content/live/wp-includes/plugin.php(524): WP_Hook->do_action(Array)\\n#4 /nas/content/live/wp-includes/class-wp-query.php(1805): do_action_ref_array('pre_get_posts', Array)\\n#5 /nas/content/live/wp-includes/class-wp-query.php(3586): WP_Query->get_posts()\\n#6 /nas/content/live/wp-includes/class-wp-query.php(3718): WP_Query->query(Array)\\n#7 /nas/content/live/wp-content/plugins/edd-hide-download/edd-hide-download.php(278): WP_Query->__construct(Array)\\n#8 /nas/content/live/wp-content/plugins/edd-hide-download/edd-hide-download.php(189): EDD_Hide_Download->query_hidden_downloads()\\n#9 /nas/content/live/wp-content/plugins/edd-hide-download/edd-hide-download.php(102): EDD_Hide_Download->hooks()\\n#10 /nas/content/live/wp-content/plugins/edd-hide-download/edd-hide-download.php(406): EDD_Hide_Download::get_instance()\\n#11 [internal function]: edd_hide_download()\\n#12 /nas/content/live/wp-content/plugins/edd-additional-shortcodes/vendor/easydigitaldownloads/edd-addon-tools/src/v1/ExtensionLoader.php(72): call_user_func('edd_hide_downlo...')\\n#13 /nas/content/live/wp-includes/class-wp-hook.php(307): EDD\\\\ExtensionUtils\\\\v1\\\\ExtensionLoader->maybeExecuteCallback('')\\n#14 /nas/content/live/wp-includes/class-wp-hook.php(331): WP_Hook->apply_filters(NULL, Array)\\n#15 /nas/content/live/wp-includes/plugin.php(476): WP_Hook->do_action(Array)\\n#16 /nas/content/live/wp-settings.php(461): do_action('plugins_loaded')\\n#17 /nas/content/live/wp-config.php(69): require_once('/nas/content/li...')\\n#18 /nas/content/live/wp-load.php(50): require_once('/nas/content/li...')\\n#19 /nas/content/live/wp-blog-header.php(13): require_once('/nas/content/li...')\\n#20 /nas/content/live/index.php(17): require('/nas/content/li...')\\n#21 {main}\\n thrown in /nas/content/live/wp-content/plugins/edd-hide-download/edd-hide-download.php on line 355",
"uuid": "ebd63d6e-cbf5-4f27-b9cb-7064b056fad0"
}
```

**Comment by dgoldak** [comment]
Another report of this error. It occurred with PHP 8.0 but downgrading to 7.4 fixed it.

36 PHP Fatal error: Uncaught TypeError: array_merge(): Argument #2 must be of type array, null given in /nas/content/live/venddstore/wp-content/plugins/edd-hide-download/edd-hide-download.php:355\nStack trace:\n#0 /nas/content/live/venddstore/wp-content/plugins/edd-hide-download/edd-hide-download.php(355): array_merge(Array, NULL)\n#1 /nas/content/live/venddstore/wp-includes/class-wp-hook.php(307): EDD_Hide_Download->pre_get_posts(Object(WP_Query))\n#2 /nas/content/live/venddstore/wp-includes/class-wp-hook.php(331): WP_Hook->apply_filters(NULL, Array)\n#3 /nas/content/live/venddstore/wp-includes/plugin.php(524): WP_Hook->do_action(Array)\n#4 /nas/content/live/venddstore/wp-includes/class-wp-query.php(1805): do_action_ref_array('pre_get_posts', Array)\n#5 /nas/content/live/venddstore/wp-includes/class-wp-query.php(3586): WP_Query->get_posts()\n#6 /nas/content/live/venddstore/wp-includes/class-wp-query.php(3718): WP_Query->query(Array)\n#7 /nas/content/live/venddstore/wp-content/plugins/edd-hide-download/edd-hide-download.php(278): WP_Query->__construct(Array)\n#8 /nas/content/live/venddstore/wp-content/plugins/edd-hide-download/edd-hide-download.php(189): EDD_Hide_Download->query_hidden_downloads()\n#9 /nas/content/live/venddstore/wp-content/plugins/edd-hide-download/edd-hide-download.php(102): EDD_Hide_Download->hooks()\n#10 /nas/content/live/venddstore/wp-content/plugins/edd-hide-download/edd-hide-download.php(406): EDD_Hide_Download::get_instance()\n#11 [internal function]: edd_hide_download()\n#12 /nas/content/live/venddstore/wp-content/plugins/edd-additional-shortcodes/vendor/easydigitaldownloads/edd-addon-tools/src/v1/ExtensionLoader.php(72): call_user_func('edd_hide_downlo...')\n#13 /nas/content/live/venddstore/wp-includes/class-wp-hook.php(307): EDD\\ExtensionUtils\\v1\\ExtensionLoader->maybeExecuteCallback('')\n#14 /nas/content/live/venddstore/wp-includes/class-wp-hook.php(331): WP_Hook->apply_filters(NULL, Array)\n#15 /nas/content/live/venddstore/wp-includes/plugin.php(476): WP_Hook->do_action(Array)\n#16 /nas/content/live/venddstore/wp-settings.php(410): do_action('plugins_loaded')\n#17 /nas/content/live/venddstore/wp-config.php(120): require_once('/nas/content/li...')\n#18 /nas/content/live/venddstore/wp-load.php(50): require_once('/nas/content/li...')\n#19 /nas/content/live/venddstore/wp-blog-header.php(13): require_once('/nas/content/li...')\n#20 /nas/content/live/venddstore/index.php(17): require('/nas/content/li...')\n#21 {main}\n thrown in /nas/content/live/venddstore/wp-content/plugins/edd-hide-download/edd-hide-download.php on line 355

**Comment by spencerfinnell** [comment]
I'm pretty sure I've seen this as a non-fatal error (not on PHP 8.0) on one of our sites. I'll try to confirm next time. I think it only pops up when the transient expires.

**Comment by spencerfinnell** [comment]
Confirmed, this is what i have seen. It's a warning on PHP 7.4:

```
Warning: array_merge(): Expected parameter 2 to be an array, null given in /wp-content/plugins/edd-hide-download/edd-hide-download.php on line 355
```

**Comment by cklosowski** [comment]
It's likely due to context and the class variable possibly not being loaded already.

We could just update `get_hidden_downloads()` to call `query_hidden_downloads()` directly. That way no matter what, it's always able to get to the end result of an array.

There should be no other reason that a `null` value comes from the `query_hidden_downloads` method, so it has to be coming from the `get_hidden_downloads()` method.

Let's just kill the entire usage of `$this->hidden_downloads` and update any references to it, to use the `query_hidden_downloads` method.
