### ISSUE TITLE
v1.2.11 Can Cause Segmentation Fault in WP CLI / Infinite Loop on Front End of Website

### ISSUE THREAD

**Issue by jakejackson1** [awesomemotive/edd-hide-download#32]
Hey EDD team,

After upgrading to 1.2.11 I noticed that if I cleared all site transients `wp transient delete --all` and then attempted another WP CLI command I'd get a Segmentation Fault error. With some debugging I worked out it was because of the EDD Hide Download plugin.

Further investigation showed that an infinite loop is created because the `query_hidden_downloads()` method makes a `WP_Query` call. That in turn triggers the `pre_get_posts()` method that is hooked in, which then calls `get_hidden_download()` and `query_hidden_download()`. This process repeats until the Segmentation Fault occurs. 

The issue isn't limited to the WP CLI either. [If none of these conditions are met](https://github.com/awesomemotive/edd-hide-download/blob/a540e98078fd9eaa8bd846127f557906c384d7b2/edd-hide-download.php#L325-L350) you'll create an infinite loop on the front end of the website when the transient is `false`. It's only after you go to the admin area of the site and the transient data can be saved correctly (because of the aforementioned conditions) that everything starts working correctly.

**Comment by cklosowski** [comment]
Thanks for the detailed report @jakejackson1 We'll see what we can do to avoid that situation.

**Comment by cklosowski** [comment]
PR is ready for testing.
